version: "3.7"
volumes:
  persistent:
services:
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - "8822:80"
  fpm:
    depends_on:
      - db
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/task_management?serverVersion=mariadb-10.6.1
    volumes:
      - ./:/var/www/project/:cached
  db:
    image: mariadb:10.6.1
    volumes:
      - ./docker/var:/var/lib/mysql
      - ./docker/build/db/:/docker-entrypoint-initdb.d/
    ports:
      - "3317:3306"
    environment:
      - MARIADB_DATABASE=task_management
      - MARIADB_ROOT_PASSWORD=password
